version: 2

snapshots:
  - name: snp_branches
    description: "snapshot data for branches table"
    columns:
      - name: branch_id
      - name: branch_name
      - name: address
      - name: status
      - name: data_date
      - name: created_at
      - name: etl_at
      - name: etl_source_model
      - name: dbt_scd_id
      - name: dbt_updated_at
      - name: dbt_valid_from
      - name: dbt_valid_to
    
  - name: snp_customers
    description: "Snapshot data for customers"
    columns:
      - name: customer_id
      - name: full_name
      - name: phone_number
      - name: email_address
      - name: identity_number
      - name: address
      - name: date_of_birth
      - name: data_date
      - name: created_at
      - name: etl_at
      - name: etl_source_model
      - name: dbt_scd_id
      - name: dbt_updated_at
      - name: dbt_valid_from
      - name: dbt_valid_to
    
  - name: snp_accounts
    description: "Snapshot data for accounts"
    columns:
      - name: account_id
      - name: customer_id
      - name: account_number
      - name: account_type
      - name: balance
      - name: status
      - name: branch_id
      - name: data_date
      - name: created_at
      - name: etl_at
      - name: etl_source_model
      - name: dbt_scd_id
      - name: dbt_updated_at
      - name: dbt_valid_from
      - name: dbt_valid_to