# -- Source -> stag
# -- Dữ liệu từ nguồn em đẩy vào stag
# -- Trong stag phải có cột để biết đc nó là ngày dữ liệu nào và thời điểm nào mình đẩy vào
# -- Bọn anh thường dùng data_date hoặc business_date làm ngày dữ liệu
# -- etl_at làm thời điểm đẩy vào
version: 2

sources:
  - name: raw              # tên schema raw trong DB
    schema: raw
    database: db_banking
    tables:
      - name: branches     # tên bảng trong schema raw
      - name: customers     
      - name: transactions   
      - name: accounts      
      - name: transaction_entries    